apiVersion: v1
kind: Service
metadata:
  name: web-lb
  annotations:
    # AWS Load Balancer Controller가 없어도 EKS는 기본 CCM이 NLB를 만들어 줌
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
