apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-msa
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames: ["order"]
  selector:
    matchLabels:
      eks-study/scrape: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
