apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: aws-sqs-auth
  namespace: order
spec:
  podIdentity:
    provider: aws
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-service
  namespace: order
spec:
  scaleTargetRef:
    name: payment-service
  minReplicaCount: 0
  maxReplicaCount: 30
  pollingInterval: 15
  cooldownPeriod: 90
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: aws-sqs-auth
      metadata:
        queueURL: https://sqs.ap-northeast-2.amazonaws.com/ACCOUNT_ID/eks-study-payments
        queueLength: "5"
        awsRegion: ap-northeast-2
        identityOwner: operator
