apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: info
  GREETING: "Hello from ConfigMap!"
  app.conf: |
    server {
      port = 8080
      mode = production
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  API_KEY: super-secret-key-do-not-commit
  DB_PASSWORD: pa$$w0rd
---
apiVersion: v1
kind: Pod
metadata:
  name: configdemo
spec:
  containers:
    - name: app
      image: alpine:3.19
      command: ["sh", "-c"]
      args:
        - |
          echo "==== ENV ===="
          env | grep -E '^(LOG_LEVEL|GREETING|API_KEY|DB_PASSWORD)='
          echo
          echo "==== Mounted file (ConfigMap) ===="
          cat /etc/app/app.conf
          echo
          echo "==== Mounted file (Secret) ===="
          cat /etc/secret/API_KEY
          echo
          echo "Sleeping 1h..."
          sleep 3600
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
      volumeMounts:
        - name: config-vol
          mountPath: /etc/app
        - name: secret-vol
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: config-vol
      configMap:
        name: app-config
    - name: secret-vol
      secret:
        secretName: app-secret
