apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: gp3
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvcdemo
spec:
  containers:
    - name: writer
      image: alpine:3.19
      command: ["sh", "-c"]
      args:
        - |
          echo "Writing to PV at $(date)..." >> /data/log.txt
          tail -f /data/log.txt
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
